"""init

Revision ID: 8b132d28dbc8
Revises: 
Create Date: 2025-04-05 15:38:43.449888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b132d28dbc8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_log_id'), 'mail_log', ['id'], unique=False)
    op.create_table('tempat_wisata',
    sa.Column('id_tempat_wisata', sa.Integer(), nullable=False),
    sa.Column('nama_tempat', sa.String(), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('jenis', sa.Enum('Alam', 'Religi', 'Buatan', name='jenis_tempat'), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('gambar', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_tempat_wisata')
    )
    op.create_index(op.f('ix_tempat_wisata_id_tempat_wisata'), 'tempat_wisata', ['id_tempat_wisata'], unique=False)
    op.create_index(op.f('ix_tempat_wisata_nama_tempat'), 'tempat_wisata', ['nama_tempat'], unique=True)
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('artikel',
    sa.Column('id_artikel', sa.Integer(), nullable=False),
    sa.Column('id_penulis', sa.Integer(), nullable=True),
    sa.Column('judul', sa.String(), nullable=True),
    sa.Column('isi', sa.String(), nullable=True),
    sa.Column('tanggal', sa.String(), nullable=True),
    sa.Column('gambar', sa.String(), nullable=True),
    sa.Column('tipe', sa.Enum('Berita', 'Promo', name='tipe-artikel'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_penulis'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_artikel')
    )
    op.create_index(op.f('ix_artikel_id_artikel'), 'artikel', ['id_artikel'], unique=False)
    op.create_index(op.f('ix_artikel_judul'), 'artikel', ['judul'], unique=False)
    op.create_table('rekomendasi_wisata',
    sa.Column('id_rekomendasi', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_rekomendasi')
    )
    op.create_index(op.f('ix_rekomendasi_wisata_id_rekomendasi'), 'rekomendasi_wisata', ['id_rekomendasi'], unique=False)
    op.create_table('sosmed_wisata',
    sa.Column('id_sosmed', sa.Integer(), nullable=False),
    sa.Column('id_tempat_wisata', sa.Integer(), nullable=True),
    sa.Column('sosmed', sa.Enum('Facebook', 'Instagram', 'Twitter', 'Youtube', 'Tiktok', name='sosial_media'), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_tempat_wisata'], ['tempat_wisata.id_tempat_wisata'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sosmed')
    )
    op.create_index(op.f('ix_sosmed_wisata_id_sosmed'), 'sosmed_wisata', ['id_sosmed'], unique=False)
    op.create_table('tiket_wisata',
    sa.Column('id_tiket', sa.Integer(), nullable=False),
    sa.Column('id_tempat_wisata', sa.Integer(), nullable=True),
    sa.Column('umur', sa.Enum('Dewasa', 'Anak-anak', name='umur'), nullable=False),
    sa.Column('hari', sa.Enum('Hari Kerja', 'Hari Libur', name='hari'), nullable=False),
    sa.Column('harga', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_tempat_wisata'], ['tempat_wisata.id_tempat_wisata'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_tiket')
    )
    op.create_index(op.f('ix_tiket_wisata_id_tiket'), 'tiket_wisata', ['id_tiket'], unique=False)
    op.create_table('rekomendasi_wisata_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rekomendasi', sa.Integer(), nullable=True),
    sa.Column('id_tempat_wisata', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_rekomendasi'], ['rekomendasi_wisata.id_rekomendasi'], ),
    sa.ForeignKeyConstraint(['id_tempat_wisata'], ['tempat_wisata.id_tempat_wisata'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rekomendasi_wisata_detail_id'), 'rekomendasi_wisata_detail', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rekomendasi_wisata_detail_id'), table_name='rekomendasi_wisata_detail')
    op.drop_table('rekomendasi_wisata_detail')
    op.drop_index(op.f('ix_tiket_wisata_id_tiket'), table_name='tiket_wisata')
    op.drop_table('tiket_wisata')
    op.drop_index(op.f('ix_sosmed_wisata_id_sosmed'), table_name='sosmed_wisata')
    op.drop_table('sosmed_wisata')
    op.drop_index(op.f('ix_rekomendasi_wisata_id_rekomendasi'), table_name='rekomendasi_wisata')
    op.drop_table('rekomendasi_wisata')
    op.drop_index(op.f('ix_artikel_judul'), table_name='artikel')
    op.drop_index(op.f('ix_artikel_id_artikel'), table_name='artikel')
    op.drop_table('artikel')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tempat_wisata_nama_tempat'), table_name='tempat_wisata')
    op.drop_index(op.f('ix_tempat_wisata_id_tempat_wisata'), table_name='tempat_wisata')
    op.drop_table('tempat_wisata')
    op.drop_index(op.f('ix_mail_log_id'), table_name='mail_log')
    op.drop_table('mail_log')
    # ### end Alembic commands ###
